### PR TITLE
Count Sorting in Java added

### PR DESCRIPTION
**Pull request by SamikshyaMstar**
Count Sort in JAVA is added!
This PR includes :
1-What is Count Sorting?
2-How it is done?
3-Code in JAVA.

### CODE REVIEW

**Review by rudradave1 — APPROVED** [review]

**Comment by SamikshyaMstar** [comment]
I am having a problem with my Hacktober fest profile @rudradave1. It shows that it's an excluded project and even after You merged my PR, the total progress is 0. kindly help me?

**Comment by rudradave1** [comment]
I am not sure, maybe @abhpd can help here.

**Comment by SamikshyaMstar** [comment]
Does any level needed to be attached like Hactoberfest accepted ? Not pretty sure my friends are saying that might happen?

**Comment by rudradave1** [comment]
No, there are no eligibility criteria. Whether you’re a student or an experienced professional, you’re welcome to participate in this challenge. Let's just hope it gets accepted or at least just learn from the experience.

**Pull request merged**
